odom_transformer:
  ros__parameters:
    base_frame: drone0/odom_base

    odoms_to_transform: ["mid360"]

    mid360:
      topic_in: /drone0/rot_odometry
      source_frame: drone0/rotated_odom
      topic_out: /drone0/odom_base


